## This is the labgrid-exporter user-configuration.
## Labgrid uses jinja2 templating for its config file.
## This file is included from configuration.yaml by a jinja2 include and can
## set some variables evaluated in configuration.yaml.

## The userconfig.yaml file is migrated between rauc installs.
## Use cp /etc/labgrid/userconfig.yaml.default /etc/labgrid/userconfig.yaml
## to go back to the most recent defaults.

## DUT-NetworkService Configuration
dut-ssh:
  NetworkService:
    address: 192.168.1.1
    username: root
    password: coffee

## TFTPProvider
tftp:
  TFTPProvider:
    internal: "/srv/tftp/"
    external: ""

## USB HUB-Ports of the TKL
{% set usb_hub = namespace(ports=[
        ('1',   'platform-3f980000.usb-usb-0:1.5.1:1.0'),
        ('2',   'platform-3f980000.usb-usb-0:1.5.2:1.0'),
        ('3',   'platform-3f980000.usb-usb-0:1.5.3:1.0'),
        ('4',   'platform-3f980000.usb-usb-0:1.5.4:1.0')]) %}

{% for idx, sysfs in usb_hub.ports %}
tkl-usb-hub-ports-p{{idx}}:
  AlteraUSBBlaster:
    match:
      'ID_PATH': '{{sysfs}}'
  AndroidUSBFastboot:
    match:
      'ID_PATH': '{{sysfs}}'
  DFUDevice:
    match:
      'ID_PATH': '{{sysfs}}'
  IMXUSBLoader:
    match:
      'ID_PATH': '{{sysfs}}'
  LXAUSBMux:
    match:
      '@ID_PATH': '{{sysfs}}'
  USBAudioInput:
    match:
      '@ID_PATH': '{{sysfs}}'
  USBDebugger:
    match:
      'ID_PATH': '{{sysfs}}'
  USBMassStorage:
    match:
      '@ID_PATH': '{{sysfs}}'
  USBSDMuxDevice:
    match:
      '@ID_PATH': '{{sysfs}}'
  USBSerialPort:
    match:
      '@ID_PATH': '{{sysfs}}'
  USBVideo:
    match:
      '@ID_PATH': '{{sysfs}}'
{% endfor %}


## Add your own exports here.

## Example for using an external USB to serial adapter and matching based
## on its serial number (instead of e.g. an USB path as below):
##example-group1-remote:
##  location: example-location-1-remote
##  USBSerialPort:
##    match:
##      'ID_SERIAL_SHORT': 'FTA8E2HP'
##    speed: 115200

## Example for using a custom baud rate of 1M baud instead of the
## 115200 baud default on the box connector:
##{% serial.baud = 1000000 %}

