## This is the labgrid-exporter user-configuration.
## Add your own exports here.

##example-group1-remote:
##  location: example-location-1-remote
##  USBSerialPort:
##    match:
##      'ID_SERIAL_SHORT': 'FTA8E2HP'
##    speed: 115200
